apiVersion: v1
kind: Service
metadata:
  name: student-portal-nodeport
spec:
  type: NodePort
  selector:
    app: student-portal
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080   # Kubernetes will use this port on the node

# kubectl apply -f service-nodeport.yaml
# kubectl get svc student-portal-nodeport
# kubectl get nodes -o wide
# Use the EXTERNAL-IP or INTERNAL-IP column value
# Example if node ip is 192.168.1.100 and nodePort 30080
# curl http://192.168.1.100:30080 | head -n 10
# kubectl scale deployment student-portal-deploy --replicas=3
# kubectl get pods -l app=student-portal
